define _GNU_SOURCE via Makefile CFLAGS
_GNU_SOURCE needs to be defined in order to enable aliases used to
access fields in struct udphdr. Fix for build issues such as:

 | packet.c: In function 'raw_packet':
 | packet.c:143:12: error: 'struct udphdr' has no member named 'source'
 |   143 |  packet.udp.source = htons(source_port);
 |	 |	      ^
 | packet.c:144:12: error: 'struct udphdr' has no member named 'dest'
 |   144 |  packet.udp.dest = htons(dest_port);
 |	 |	      ^
 | packet.c:145:12: error: 'struct udphdr' has no member named 'len'
 |   145 |  packet.udp.len = htons(sizeof(packet.udp) + sizeof(struct dhcpMessage)); /* cheat on the psuedo-header */
 |	 |	      ^
 | packet.c:146:32: error: 'struct udphdr' has no member named 'len'
 |   146 |  packet.ip.tot_len = packet.udp.len;
 |	 |				  ^
 | packet.c:148:12: error: 'struct udphdr' has no member named 'check'
 |   148 |  packet.udp.check = checksum(&packet, sizeof(struct udp_dhcp_packet));
 |	 |	      ^

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>